name = "ops-excellence-d1"
main = "src/index.ts"
compatibility_date = "2024-03-20"

[[d1_databases]]
binding = "DB"
database_name = "ops-excellence-history"
database_id = "291bb3dd-fe2e-49f7-96d6-b9384492ea83"

